### ISSUE TITLE
Docker image build failed

### ISSUE THREAD

**Issue by GeekArthur** [annieke/rosetta-ethereum#19]
**Describe the bug**
the rosetta implementation docker images build from latest master branch is failed, the reason is [this line](https://github.com/annieke/rosetta-ethereum/commit/23944c75e7f7877e0dbc074388c9b1b7c6af0e1a#diff-6e93f10762134aaa358b850881ed5213b28349e0f1ac872e7bb76804e761d3dcR42) uses the util function `utils.LoadAndParseURL(genesisFile, &genesisAllocations)` from https://github.com/coinbase/rosetta-sdk-go/tree/master/utils package but the function doesn’t define in the https://github.com/coinbase/rosetta-sdk-go/tree/master/utils package. I saw the PR is from Inphi, I guess probably Inphi added the util function locally?
The error:
```
#20 105.8 optimism/bootstrap.go:42:13: undefined: utils.LoadAndParseURL
------
executor failed running [/bin/sh -c cd src   && go build]: exit code: 2
make: *** [build-local] Error 1
```

**Comment by Inphi** [comment]
Should be fixed. Please rerun bootstrap-gen with the latest rosetta on master.

**Comment by GeekArthur** [comment]
@Inphi The docker image build issue is fixed, however I can still see the negative balance on testnet with the latest `bootstrap_balances.json`, I will add details to https://github.com/annieke/rosetta-ethereum/issues/9 and close this issue.
